### ISSUE TITLE
klet

### ISSUE THREAD

**Issue by richardalligier** [mathiasbourgoin/SPOC#31]
Hi,

I am struggling with the "klet" word. As far as I understand, it can be used to define functions that can be used inside a kernel ?!

I define a  point type
`ktype point = {x:float;y:float}`
A function that does nothing
`klet id = fun p -> {x=p.x;y=p.y}`
And finally my kernel
`let toy = kern c n ->
  let open Std in
  let i = thread_idx_x + block_dim_x * block_idx_x in
  if i < n then c.[<i>] <- id {x=1.;y=2.}`

And then when I compile I have an error

> Failure:  "error get_ff_type_str -> Custom point"

if I delete the call to `id` in the kernel and the definition of `id`, the code run just fine with a vector defined as `let c =  Vector.create (Vector.Custom customPoint) n in`

I don't get what is the error here. I am not sure how to use the `klet` word.

**Comment by richardalligier** [comment]
Here is my full code:

```
open Spoc
open Kirc

ktype point = {x:float;y:float}

(*klet id = fun p -> {x=p.x;y=p.y}*)

let toy = kern c n ->
  let open Std in
  let i = thread_idx_x + block_dim_x * block_idx_x in
  if i < n then c.[<i>] <- (*id*)  {x=1.;y=2.}

let () =
  let devs = Spoc.Devices.init () in
  let dev = devs.(0) in
  let n = 100 in
  let c =  Vector.create (Vector.Custom customPoint) n in
  ignore(Kirc.gen ~only:Devices.OpenCL toy);
  let threadsPerBlock = match dev.Devices.specific_info with
    | Devices.OpenCLInfo clI ->
      (match clI.Devices.device_type with
       | Devices.CL_DEVICE_TYPE_CPU -> 1
       | _ -> 256)
    | _ -> 256
  in
  let blocksPerGrid = (n + threadsPerBlock -1) / threadsPerBlock in
  let block = {Spoc.Kernel.blockX = threadsPerBlock;
               Spoc.Kernel.blockY = 1;
               Spoc.Kernel.blockZ = 1;} in
  let grid = {Spoc.Kernel.gridX = blocksPerGrid;
              Spoc.Kernel.gridY = 1;
              Spoc.Kernel.gridZ = 1;} in
  let name = dev.Spoc.Devices.general_info.Spoc.Devices.name in
  Kirc.run toy ( c, n) (block,grid) 0 dev;
  let i = 0 in
  let p = Spoc.Mem.get c i in
  Printf.printf "\n%f %f" p.x p.y;
```

Just to give you a piece of code you are familiar with, if I try to compile SPOC-master/SpocLibs/Sarek/extension/tests/ray.ml, I have first this error:

`File "ray.ml", line 40, characters 5-14:
Parse error: = then fun expected after [ident] (in [str_item])`
I assumed that `kfun` is deprecated or something and replaced it by `fun`. And when I compile it, I have an error similar to the one I get with my toy example::
```
ocamlfind ocamlopt  \
-pp "camlp4 -I `ocamlfind query sarek_syntax` -parser o -printer o kernels_int.cma" \
-thread -package ctypes.foreign,spoc,sarek,fastflow,graphics -linkpkg \
ray.ml  -o ray.asm
RECORD
File "ray.ml", line 44, characters 4-5:
Failure: "error get_ff_type_str -> Custom point3"
File "ray.ml", line 1:
Error: Error while running external preprocessor
Command line: camlp4 -I /home/alligier/.opam/4.04.0/lib/sarek_syntax -parser o -printer o kernels_int.cma 'ray.ml' > /tmp/ocamlppbf8b7e

Makefile:4: recipe for target 'asm' failed
make: *** [asm] Error 2
```

**Comment by mathiasbourgoin** [comment]
Hi,

There was indeed a problem with an experimental library we're working on that shouldn't have been used in the master branch of SPOC.

As you stated `kfun` is now deprecated and `fun` should be used instead with `klet`.

I also made a few modifications to repair the **ray.ml** test sample.

**Comment by richardalligier** [comment]
Merci pour ta réponse/correction rapide !
