### ISSUE TITLE
should we update the packages in opam?

### ISSUE THREAD

**Issue by UnixJunkie** [mathiasbourgoin/SPOC#41]
in opam, there is spoc and sarek at version: 20140620.
should we update both of them and to what version for each?

**Comment by mathiasbourgoin** [comment]
Hi,

The opam package is really old, It's probably better to directly
compile/install it from the github repository.

I can prepare an updated opam package if you prefer.

By the way, I saw your e-mail in the OCaml mailing list.
I'm not sure you'll find a SPOC user base there but there are some users
(mostly academics).
To answer your question, SPOC is pretty stable and I'm confidant that it
can be used in large projects, however Sarek (the DSL) is still
experimental.
If you need any help, feel free to contact me. I will answer your within a
few days (maybe a little more in July/August).

I hope you'll try it and give me your feedback.

Thanks for your mail and your interest in SPOC.

Mathias

2017-07-21 4:41 GMT+02:00 Francois BERENGER <notifications@github.com>:

**Comment by UnixJunkie** [comment]
if you create a new tag, I can update the opam package

**Comment by UnixJunkie** [comment]
I prefer to work using tagged versions of things

**Comment by UnixJunkie** [comment]
cf. https://github.com/ocaml/opam-repository/pull/9918
